# Generated by Django 4.0.3 on 2022-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Текст'),
        ),
    ]
