# Generated by Django 4.0.3 on 2022-04-12 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.ManyToManyField(blank='True', related_name='viewed', to=settings.AUTH_USER_MODEL, verbose_name='Просмотрено'),
        ),
    ]
