# Generated by Django 4.0.2 on 2022-04-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_status_alter_myuser_favorite_alter_myuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.status', verbose_name='Статус'),
        ),
    ]
